[package]
name = "sveltum-axum-layer"
version = "0.1.0"
edition = "2024"

[dependencies]
# Error type
anyhow = "1"

# Bytes type
bytes = "1"

# HTTP and HTTP body types
http = "1.3.1"
http-body-util = "0.1.3"

# Tower services and tower http for ServeDir
axum-core = "0.5.2"
tower-http = { version = "0.6.2", features = ["fs"] }
tower-service = "0.3.3"

sveltum = { version = "0.1.0", path = "../sveltum" }
