[package]
name = "sveltum-axum-layer"
version = "0.1.0"
edition = "2024"

[dependencies]
# Error type
anyhow = "1"

# Bytes type
bytes = "1"

# HTTP and HTTP body types
http = "1.3.1"
http-body-util = "0.1.3"

# Tower services and tower http for ServeDir
axum-core = "0.5.2"
tower-service = "0.3.3"

sveltum = { version = "0.1.0", path = "../sveltum" }
futures-util = "0.3.31"
pin-project-lite = "0.2.16"
http-body = "1.0.1"
tokio-util = { version = "0.7.15", features = ["full"] }
tokio = { version = "1.44.2", features = ["full"] }
percent-encoding = "2.3.1"
http-range-header = "0.4.2"
mime_guess = "2.0.5"
mime = "0.3.17"
tracing = "0.1.41"
httpdate = "1.0.3"
thiserror = "2.0.12"
